"""removePriceService

Revision ID: 78575274742d
Revises: 18f181e28a51
Create Date: 2024-11-27 22:38:56.923949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78575274742d'
down_revision = '18f181e28a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('time_required')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('time_required', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
